Lang.prototype.pack.en = {
	"token": {
		//标题
		"福华客户关系管理系统":"Fuhua CRM System",
		"业务员":"User",
		//--货代物流部分
	   	"货代":"Freight forwarding",
	   	// "月份":"Month",
	   	"客服得分":"Service",
	   	"价格得分":"Price",
	   	"仓储得分":"Warehouse",
	   	"投诉反馈得分":"Complaints",
	   	"总评分":"Total points",
	   	"评价详情":"Evaluation details",
	   	"备注":"Remarks",
	   	"修改原因":"Modify reason",
	   	"评价时间":"Evaluate time",
	   	"评价人":"Valuator",
	   	"创建者":"Creator",
	   	"上一次修改者":"Last modify user",
	   	// "创建时间":"Create time",
	   	"修改时间":"Modify time",
	   	"类型":"Type",
	   	"社会信用代码":"Credit code",
	   	"办公地址":"Office address",
	   	"联系人":"Contacts",
	   	// "联系电话":"Tel",
	   	// "邮箱":"Email",
	   	"运输方式":"Transportation methods",
	   	"货代备注":"Freight forwarding remarks",
	   	"营业执照":"Business licence",
	   	"经营资格登记证":"Registration certificate",
	   	"合作时间":"Cooperate time",
	   	"综合评分":"Overall rating",
	   	"仓库":"Warehouse",
	   	"仓库面积":"Warehouse area",
	   	"是否危险":"Danger",
	   	"是否内装进港":"Built into the port",
	   	"仓库地址":"Warehouse address",
	   	"报表及时性":"Reports timely",
	   	"报表准确性":"Reports accurately",
	   	"入库":"Storage",
	   	"换包装":"Package",
	   	"盘库":"Check stock",
	   	"竞标记录":"Bid",
	   	"仓库名称":"Warehouse name",
	   	"月份":"Month",
	   	"货代订单":"Forwarder order",
	   	//--客户信息
	   	"客户联系人ID":"Linkman ID",
	   	"客户ID":"Customer ID",
	   	// "姓名":"Name",
	   	// "联系电话":"Link phone",
	   	// "岗位":"Posts",
	   	// "负责区域":"Response area",
	   	// "是否在职":"On job",
	   	// "性别":"Sex",
	   	"生日":"Birthday",
	   	// "国籍":"Natonality",
	   	"影响力情况":"Infuence",
	   	"展会习惯":"Exhibition habits",
	   	"喜好":"Fancy",
	   	"饮食习惯":"Eating habits",
	   	"宗教信仰":"Faith",
	   	// "是否默认":"Is default",
	   	"企业全称":"Full name",
	   	"企业简称":"Short name",
	   	"企业类型":"Enterprise type",
	   	"地区分类":"Area",
	   	// "国家":"Country",
	   	"注册资金":"Registered funds",
	   	// "注册地址":"Registered address",
	   	// "经营范围":"Management scope",
	   	"中信保编号":"Sinosure number",
	   	"中信保信用评级":"Sinosure level",
	   	"百科备注":"Parent remarks",
	   	// "企业电话":"Enterprise phone",
	   	// "企业邮箱":"Enterprise email",
	   	// "企业简介":"Enterprise profile",
	   	// "发展历程":"Development course",
	   	// "销售网络":"Sales network",
	   	// "自定义字段":"Custome field",
	   	"企业信息完成度":"Customer completion",
	   	"年":"Year",
	   	"标准产品":"Product",
	   	"产品名称":"Product name",
	   	"年需求量":"Annual demands",
	   	"平均单价":"Average price",
	   	"供应商":"Supplier",
	   	"年采购量":"Purchase amount",
	   	"品牌":"Brand",
	   	"营销手段":"Marketing method",
	   	"年销量":"Year sales",
	   	"销售目的国":"Destination country",
	   	"主要采购商":"Main pruchaser",
	   	"企业性质":"Property",
	   	"企业性质备注":"Property remarks",
	   	"客户子公司备注":"Customer sub remarks",
        "公司别名（子公司信息）表":"Company aliases table",
        "公司别名（子公司信息）":"Company aliases",
		"请选择信用评级":"Chose credit rating",
		"快速查询":"Quick search",
		"输入企业性质":"Input enterprise property",
		"潜在":"Potential",
		"合作":"Cooperate",
		"流失":"Lost",
	   	//--拜访客户
	   	"拜访记录":"Visit record",
	   	// "客户联系人ID":"Linkman id",
	   	"单人费用":"Activity expens",
	   	"单人礼物":"Activity gift",
	   	"业务员id":"Salesman Id",
	   	"业务员名称":"Salesman name",
	   	"开始时间":"Start time",
	   	"结束时间":"End time",
	   	"活动类型":"Activity type",
	   	"活动类型备注":"Activity remarks",
	   	"活动地点":"Activity address",
	   	"总活动费用":"Activity expense",
	   	"拜访对象备注":"Visit remarks",
		"拜访对象":" visited object",
	   	"活动摘要":"Activity summary",
	   	"客户级别":"Customer level",
	   	"客户状态":"Customer state",
	   	"客户流失备注":"Lost remarks",
	   	"是否有中国分公司":"China branch office",
	   	"是否有中方采购合同":"China contract",
	   	"资质文件":"Qualification documents",
	   	"销售客户备注":"Sale remarks",
	   	"机会来源类型":"Opportunity type",
	   	"机会来源说明":"Opportunity sources",
	   	"机会来源描述":"Price sensitive",
	   	"忠诚度":"Loyalty",
	   	"开始合作时间":"Cooperate time",
	   	"采购季节":"Procurement season",
	   	"紧密度":"Affinity",
	   	"活跃周期":"Active period",
	   	"合作备注":"Cooperate remarks",
	   	"总销售额":"Total sales revenue",
	   	"总最低销售售价":"Lowest sale money",
	   	"总维护费用":"Total maintenance costs",
	   	"总利润":"Total profits",
	   	"加工厂位置":"Factory locate",
	   	"工厂生产线":"Factory product line",
	   	"加工产品":"Factory product",
	   	"单据要求":"Document require",
	   	"对船公司要求":"Shipping agent require",
	   	"装箱要求":"Package require",
	   	"出运货物":"Goods type",
	   	"免用箱期":"Mianxiangqi",
	   	"免推期":"Miantuiqi",
	   	"是否可以转运":"Transport flag",
	   	"是否分批出运":"Batch flag",
	   	"交单地址要求":"Presentation address",
	   	"费用(元)":"Expense(¥)",
        "费用":"Expense",
	   	"赠送礼物":"Gift giving",
	   	"活动摘要":"Activity summary",
	   	//--加工厂
	   	"生产许可证":"Production licenses",
	   	"农药登记证":"Pesticide registration",
	   	"排污许可证":"Discharge permit",
	   	"工厂管理人员":"Factory manage person",
	   	"产品信息":"Product info",
	   	"工厂备注":"Factory remarks",
	   	"企业代码":"Enterprise code",
	   	//--客户产品
	   	"包材要求":"Ppackaging require",
	   	"特殊要求":"Special require",
	   	"产品浓度":"Concentration",
	   	"盐类":"Salt type",
	   	"其它盐":"Other salt name",
	   	"执行标准":"Execute standard",
	   	"执行标准号":"Execute numer",
	   	"标准备注说明":"Execute remarks",
	   	"产品特点":"Product feature",
	   	"产品要求":"Product demand",
	   	"加工成分":"Processing components",
	   	"理化指标":"Physical properities",
	   	"颜色属性":"Product color",
	   	"包装信息":"Package info",
	   	"执行标准":"Execute standard",
	   	"执行标准号":"Execute numer",
	   	"标准备注说明":"Execute remarks",
	   	"产品数量":"Product amount",
	   	"产品单位":"Product unit",
	   	"内包装要求":"Inside package require",
	   	"内包装要求单位":"Inside package require unit",
	   	"内包装要求名称":"Inside package require name",
	   	"外包装要求":"Outside package require",
	   	"外包装要求单位":"Outside package require unit",
	   	"外包装要求名称":"Outside package require name",
	   	"标准内包装id":"Inside package id",
	   	"标准内包装名称":"Inside package name",
	   	"标准内包装信息":"Inside package info",
	   	"标准内包装价格":"Inside package price",
	   	"标准外包装id":"Outside package id",
	   	"标准外包装名称":"Outside package name",
	   	"标准外包装信息":"Outside package info",
	   	"标准外包装价格":"Outside package price",
	   	"标准辅材id信息":"Sub package info",
	   	"标准辅材价格":"Sub package price",
	   	"加工成分费用":"Processing price",
	   	"颜色属性":"Product color",
	   	"图片信息":"Image info",
	   	"运输信息":"Freight info",
	   	"运输价格":"Freight price",
	   	"内部供货单位":"Inside unit",
	   	"内部核算价":"Inside price",
	   	"交货时间":"Delivery date",
	   	"单据要求":"Documentary require",
	   	"对船公司要求":"Shipping agent require",
	   	"装箱要求":"Package require",
	   	"出运货物":"Goods type",
	   	"免箱期":"Free detention",
	   	"免堆期":"Free demurrage",
	   	"是否可以转运":"Transport flag",
	   	"是否分批出运":"Batch flag",
	   	"柜子规格":"Cupboard type",
	   	"整柜数量":"Cupboard per number",
	   	"柜数":"Cupboard number",
	   	"海运费估算":"Ocean freight",
	   	"港杂费":"Port surcharge",
	   	"出口退税率":"Tax free",
	   	"最低销售价":"Min sell price",
	   	"合同单价":"Contract price",
	   	//--商机
	   	"商机名称":"Business name",
	   	"商机来源":"Business from",
	   	"商机状态":"Business state",
	   	"预计收益":"Expect income",
	   	"成功概率":"Success probability",
	   	"商机描述":"Business describe",
	   	"商机备注":"Business remarks",
	   	"失败原因":"Fail reason",
	   	"币种":"Currency",
	   	"汇率":"Exchange rate",
	   	"付款方式":"Pay type",
	   	"账期":"Payment days",
	   	"目的港":"Destination port",
	   	"目的国家":"Destination country",
	   	"贸易方式":"Trade type",
	   	"贸易方式说明":"Trade descripe",
	   	"佣金方式":"Commission mode",
	   	"佣金率":"Commission percent",
	   	"信保赔付率":"Credit rate",
	   	"福华收款银行":"Bank",
	   	"订单总价":"Total order price",
	   	"跟进内容":"Follow content",
	   	"跟进效果":"Follow effect",
	   	"商机阶段":"Business process",
	   	"转化状态":"Transform state",
	   	//--知识库
	   	"问题标题":"title",
	   	"解决方案":"solution",
	   	"文档资源地址":"resource_url",
	   	"包装参数":"package_param_detail",
	   	"颗粒剂加工费":"granule_processing_fee",
	   	"成分价格":"component_price",
	   	"管理费用":"management_fee",
	   	"港杂费":"terminal_handing_charges",
	   	"运费维护":"transportation_fee",
	   	"水剂加工费":"wateragent_fee",
	   	"展会名称":"name",
	   	"城市":"city",
	   	"展会地址":"address",
	   	"开始时间":"start_time",
	   	"结束时间":"end_time",
	   	"主办方":"sponsor",
	   	"承办方":"organizer",
	   	"展会介绍":"introduce",
	   	"展会链接":"link_url",
		//--hahaha
		"客户信息":"Consumers",
		"客户列表":"Consumers list",
		"供应商信息":"Suppliers",
		"加工厂":"Processing plant",
		"货代物流":"Freight agent & Logistics",
		"销售统计":"Sales statistics",
		"商机":"Business opportunity",
		"销售动态":"Sales dynamic",//?
		"费用与利润":"Expenses&Profit",
		"客户维护":"Customer care",
		"利润统计":"Profit statistics",
		"我的历史订单":"My history Order",//?
		"市场数据":"Market data",
		"行业数据":"Industry data",
		"知识库":"Knowledge",
		"产品常见问题":"Product's FAQ",
		"营销培训":"Sales Training",
		"客户产品包装要求":"Customization package",
		"标准产品档案":"Standard products",
		"包材档案":"Packages",
		"包材成本参考":"Packing cost",
		"加工成本参考":"Processing cost",
		"百科":"Encyclopedia",
		"展会动态":"Exhibition dynamic",
		"其他":"Else",
		"决策支持":"Decision",
		"销售数据":"Sale data",
		"成本费用":"Cost",
		"数据库":"Database",
		"系统管理":"System",
		"权限设置":"Purview setting",
		"数据字典维护":"Data dictionary maintenance",
		"修改密码":"Modify password",
		"退出":"Exit",
		"当前位置":"Position",
		"上一页":"Previous Page",
		"下一页":"Next Page",
		"确定":"Confirm",
		"取消":"Cancel",
		"完成":"Finished",
		"继续添加产品":"Continue to add products",
		"输入关键词查找":"Enter keywords",
		"搜索":"Search",
		"新增":"Add",
		"基本信息":"Basic info",
		"市场信息":"Market info",
		"订单信息":"Order info",
		"关联数据":"Related data",
		"订单默认要求":"Order default request",
		"沟通记录":"Communication record",
		"编辑":"Edit",
		//--树形结构部分
		"美洲":"America",
		"亚洲":"Asia",
		"欧洲":"Europe",
		"非洲":"Africa",
		"大洋洲":"Oceania",
		"南美洲":"South America",
		"北美洲":"North America",
		"东亚":"East Asia",
		"韩国":"South korea",
		"日本":"Japan",
		"朝鲜":"North Korea",
		"东南亚":"Southeast Asia",
		"西亚":"west Asia",
		"南亚":"South Asia",
		"西欧":"Western Europe",
		"东欧":"Eastern Europe",
		"北欧":"Northern Europe",
		"南非":"South Africa",
		"加纳":"Ghana",
		"澳大利亚":"Australia",
		"新西兰":"New Zealand",
		"订单记录":"Order record",
		"调价记录":"Adjust price record",
		"延付款记录":"Delay payment record",
		"合同取消记录":"Contract cancel record",
		//--下拉框部分
		"合作客户":"Cooperative client",
		"潜在客户":"Potential customer",
		"流失客户":"Lost customer",
		"信用评级":"Credit rating",
		"分销商":"Distributor",//?
		"经销商":"Wholesaler",//?
		"终端客户":"Terminal clients",
		"客户类型":"Client type",
		"战略客户":"Strategic client",
		"大客户":"Major client",//?
		"重要客户":"Important client",//?
		"一般客户":"Ordinary client",
		"风险客户":"Unstable customers",
		"客户状态":"Customer status",
		"正常":"Normal",
		"客户编号":"Customer ID",
		"易流失":"Instability",
		"销售组织":"Marketing organizing",
		"全部":"All",
		"付款方式":"Payment method",
		"预付":"Advance payment",
		"账期":"Payment days",
		"补贴":"Subsidy",
		"调价方式":"Adjust price method",
		"上调":"Up-regulation",
		"下调":"Down-regulation",
		"是":"Yes",
		"否":"No",
		//--表格部分
		"客户全称":"Customer's full name",//?
		"客户简称":"Customer's shotr name",//?
		"国家":"Country",
		"开始合作时间":"Time to start cooperation",
		"合作时间（月）":"Collaboration time(Month)",
		"活跃周期":"Active Period",
		"合同总金额（万元）":"Contract total amount(Million)",
		"总最低销售限价（万元）":"Total minimum selling price(Million)",
		"总维护费用（万元）":"Total maintenance costs(Million)",
		"总利润（万元）":"Gross profit(Million)",
		"产品名称":"Product name",
		"产品种类":"Product category",
		"总销售量":"Total revenue",
		"采购产品":"Purchase product",
		"供应商":"Supplier",
		"年需求量":"Annual demand",
		"年采购量":"Annual purchases",
		"平均单价（美元）":"Average unit price($)",
		"销售产品":"Product sold",//?
		"品牌":"Brand",
		"营销手段":"Marketing method",
		"年销售量":" Annual sales",
		"销售目的国":"Destination-contry of sales",
		"所占市场份额":"Share of the market",
		"合作情况":"Collaborations",
		"价格敏感度":"Price sensitive",
		"忠诚度":"Loyalty",
		"采购季节":"Purchase season",
		"合作紧密度（福华是否独家供应）":"Cooperation cohesion(whether Fuhua is the exclusive supplier)",
		"活跃周期":"Active Period",
		// "备注":"Remark",
		"编号":"Number",
		"姓名":"Name",
		"岗位":"Position",
		"是否在职":"In-service",
		"负责区域":"Areas of responsibility",
		"性别":"Gender",
		"国籍":"Nationality",
		"联系电话":"Telephone",
        "联系电话1":"Telephone1",
        "联系电话2":"Telephone2",
		"邮箱":"Email",
		"是否默认":"Default",
		"产品序列号":"Serial number",
		"品名":"Product name",
		"品类":"Product category",
		"包装规格":"Packaging standard",
		"产品参数":"Product parameter",
		"包装参数":"Packaging parameter",
		"订单编号":"Order number",
		"外销合同号":"Export contract number",
		"合同成本价（万元）":"Contract cost price(Million)",
		"是否投诉":"Complaint",
		"是否调价":"Price adjustment",
		"利润（万元）":"Profit(Million)",
		"是否质押":"Pledge",
		"合同时间":"Contract time",
		"调价单价金额":"The price unit price amount",
		"合同价总变更":"The total contract price alteration",
		"调价原因":"Adjustment reason",
		"操作人":"Operator",
		"调价日期":"Price adjustment date",
		"发票号":" Invoice number",
		"工厂":"Factory",
        "经销商":"Dealer",
        "分销商":"Distributor",
        "终端客户":"End customer",
		//--表单部分
		"中信保编码":"Sinosure number",
		"查看报告":"View report",
		"注册资金（美元）":"Registered capital($)",
		"企业电话":"Corporate telephony",
		"企业邮箱":"Corporate email",
		"注册地址":"Registered address",
		"经营范围":"Business scope",
		"是否有中国分公司":"China branch",
		"是否有中方采购":"Chinese  procurement",
		"工厂位置":"Factory Location",
		"生产线":"Production line",
		"产品":"Product",
		"产能":"Productivity",
		// "备注":"Remark",
		"创建人":" Creator",
		"创建时间":" Creation time",
		"客户百科":"Customer encyclopedia",
		"企业简介":"Company profile",
		"发展历程":" Development history",
		"销售网络":"Sales network",
		"自定义字段":"Custom field",
		"最后编辑人":"The last editor",
		"编辑时间":"Edit time",
		"开始时间":"Start time",
		"结束时间":"End time",
		//补充
		"返回":"Back",
		"机会来源":"Opportunity source",
		"机会描述":"Opportunity description",
		"重置":"Resetting",
		"默认联系人":"Default contacts",
		"状态":"State",
		"潜在客户列表":"Potential customer table",
		"金额单位：万元":"Currency Unit : Million",
		"合同总金额":"Contract total amount",
        "总最低销售限价":"Total minimum selling price",
		"已回款金额":"Amount paid",
		"净利润" :"Net profit",
        "合作客户列表":"Cooperative client table",
		"邮件":"Email",
		"导航":" Navigation",
		"订单记录表":"Order record table",
        "开始日期":"Start data",
        "结束日期":"End data",
        "利润":"Profit",
        "合同成本价":"Contract cost price",
		"客户商品名":"Customer product name",
        "品类序列号":"Product category serial number",
		"规格":"Standard",
		"型号":"Model",
		"主单位":"Primary unit",
		"销售流程":"Sales process",
        "保存":"Save",
		"菜单管理":"Menu management",
		"角色管理":"Role management",
        "流失客户列表":"Lost customer table",
		"流失原因分析":"Cause Analysis of loss",
		"订舱出运要求":"Shipment booking requirement",
		"对船运公司要求":"Requirements for shipping company",
        "打托（缠膜）":"Palletizing(Wrap)",
		"免熏蒸托盘":"Non fumigation pallet",
		"熏蒸托盘":"IPPC",
		"塑料托盘":"Plastic pallet",
		"订制托盘":"Customized pallet",
		"帖唛":"",
		"垫板":"Plate",
		"纸板":"Carton",
		"气囊":"Air bag",
		"拉网":"Seine",
		"紧固带":"Fastening ring",
		"抄条码":"",
		"美式门封":"American door seal",
		"护条":"Joint",
		"护角":"Corner protector",
		"是否需要监装":"Inspection of storage",
		"商检":"Inspection",
		"法检":"Legal examine",
		"输入机构名称":"Input the organization name",
		"吨桶是否铁丝固定":"Bucket wire fixation",
		"普货":"Normal goods",
		"危险品":"Dangerous goods",
		"天":"day",
		"是否拜访":"Visit",
        "远程沟通":"Tele-Communication",
		"出差拜访":"On business visits",
		"展会邀请":"Exhibition invitation",
		"工厂参观":"Factory Visit",
		"商务宴请":"Business Dinner",
		"其他(备注内容)":"Else(remark)",
		"分销主要竞争对手":" Major distribution competitors",
		"编辑百科":"Edit encyclopedia",
		"报价":"Quoted price",
		"订单":"Order",
		"新增商机":"Add business opportunity",
		"直接报价":"Quoted price directly",
        "商机列表":"Business opportunity table",
		"客户名称":"Customer name",
		"剩余时间(日)":"Remaining time(day)",
		"商机编号":"Opportunity number",
        "展会":"Exhibition",
		"门户网站":"Portal",
		"农药店考察":"Pesticide store investigation",
		"客户介绍":"Customer Introduction",
		"主动联系":"Contact initiative",
        "待报价":"Stay offer",
		"失败":"fail",
		"已转化":"Converted",
        "出具海运提单":"Bill of shipping",
        "出具货运提单":"Bill of freight",
        "是否需要发票":"Commercial invoice",
        "是否需要箱单":"Packing list",
        "是否需要质检单":"Analysiscertificate",
		"是否需要保单":"Warranty",
		"是否出COO":"COO",
        "是否需要危包证":"DG Packing certificate",
        "是否需要受益人证明":"Beneficiary certificate",
        "是否出熏蒸证书":"Fumigation Certificate",
        "是否需要MSDS":"MSDS",
        "提单是否电放":"Telex release when B/L",
        "是否需要银行交单":"Present the documents to bank",
        "是否需要做第三方检测，并出具检测报告":"Do th third part testing, and issue testing report",
        "是否需要Packing Declaration":"Packing Declaration",
        "是否需要Import Container Weight Declaration":"Import Container Weight Declaration",
        "是否需要Manufacturer's Certificate":"Manufacturer's Certificate",
        "其他单据要求":"Other bills",
        "直接电放":"Telex release directly",
        "正本出后电放":"Telex release after original",
        "商检局":" Inspection Bureau",
        "贸促会":"CCPIT",
        "普通":"Normal",
        "报价列表":"Quoted price table",
        "订单产品":"Sales order detail",
        "订单列表":"Order table",
        "订单状态":"Order state",
        "待下单":"Waiting order",
        "已下单":"Already ordered",
        "万元":"Million",
        "客户国别":"Client country",
        "意向产品1":"Interested product1",
        "预计采购量1":"Estimate purchase amount 1",
        "意向产品2":"Interested product2",
        "预计采购量2":"Estimate purchase amount 2",
        "预计截止日期":"Estimate deadline",
        "创建日期":"Creation date",
        "跟进记录":"Follow-up record",
        "商机跟进":"Opportunity follow-up",
        "费用和利润":"Expenses&profit",
        "销售额":"Sales revenue",
        "毛利润":"Gross margin",
        "营销成本":"Marketing cost",
        "总额":"Total amount",
        "按地区":"By Area",
        "按客户":"By Customer",
        "按业务员":"By Salesman",
        "按产品":"By Product",
        "销售最低限价":"Minimum selling price",
        "地区内国家排名明细":"Detailed ranking of countries in the region",
        "排名":"Ranking",
        "地区分类排名":"Area classification ranking",
        "国家排名":"National ranking",
        "客户利润明细":"Customer profit details",
        "销售量":"Sales volume;",
        "毛利率（%）":"Rate of margin(%)",
        "合同号":"Contract number",
        "标题":"Title",
        "上传人":"Author",
        "上传时间":"Time Uploaded",
        "可否下载":"Download",
        "承办单位":"Organizer",
        "展会介绍链接":"Introduction link",
        "成都":"Chengdu",
        "西藏":"Tibet",
        "北京":"Beijing",
        "详细地址":"Complete address",
        "展会新增":"Exhibition New",
        "完整度":";Completion",
        "最后编辑时间":"Last edited time",
        "客户":"Customer",
        "竟对":"Competitor",
        "新增/编辑百科":"Add/Edit Encyclopedia",
        "添加字段":"Add field",
        "百科详情":"Encyclopedia Info",
        "制剂加工费":"Agent processing fees",
        "国内运费":"Inland transportation fees",
        "费率":"Tariff",
        "人工费":"Labour cost",
        "杂费":"Sundry fees",
        "主材规格":"Main material standard",
        "单价（元/每千升或每吨）":"Price（Yuan/KL(T))",
        "价格有效期":"Price validity",
        "水、电、气费（元/吨）":"Water/Electricity/Gas fees(Yuan/T)",
        "利润（元/吨）":"Profit(Yuan/T)",
        "管理费（元/吨）":"Management fee(Yuan/T)",
        "税金（元/吨）":"Tax(Yuan/T)",
        "费用合计":"Total fees",
        "起运城市":"Departure city",
        "目的城市":"Destination city",
        "成分名称":"Ingredients name",
        "适合产品":"Suitable for producte",
        "单耗（千克/吨）":"Piece yardage(kg/T)",
        "单价（元/千克）":"Price(Yuan/Kg)",
        "港杂费参考价":"Port sur-charge reference price",
        "项目":"Item",
        "一般化工品":"General chemicals",
        "毛利率":"Rate of margin",
        "币种&汇率":"Currency&Exchange rate",
        "其他费率":"Other Exchange rate",
        "有效期":"Validity",
        "产品分类":"Product Category",
        "主计量单位":"The main units of measurement",
        "规格型号":"Specification",
        "含量":"Content",
        "无":"None",
        "异丙胺盐":"Isopropylamine",
        "铵盐":"Ammonium",
        "钾盐":"potassium salt",
        "常见问题":"FAQ",
        "问题内容":"Content",
        "附件":"Attachment",
        "上传":"Upload",
        "二钾铵盐":"Dipotassium salt",
        "加工成份":"Processing components",
        "包材类型名称":"Package Type Names",
        "材质":"Material",
        "质量指标":"Quality Index",
        "质量指标数值":"Quality Index values",
        "单价（元）":"Price(Yuan)",
        "适用剂型":"Suitable Dosage Form",
        "包材分类":"Package Classification",
        "单价":"Price",
        "单耗":"Piece yardage",
        "尺寸":"Size",
        "原药":"Technical material",
        "水剂":"Water aqua",
        "颗粒剂（粉剂）":"Granules(Powdered)",
        "图片":"Picture",
        "继续添加":"Continue adding",
        "已启用":"Enabled",
        "已禁用":"Disabled",
        "关联包材":"Related packaging material",
        "包材类型编号":"Package type Number",
        "单耗（每千升或每吨）":"Piece yardage(KL/T)",
        "新增关联":"Add Related",
        "删除关联":"Delete Related",
        "(元/kg)":"(Yuan/kg)",
        "继续添加适应产品":"Continue adding suitable product",
        "男":"Male",
        "女":"Female",
        "商机阶段":"Generating a deal flow",
        "跟进内容":"Follow-up content",
        "跟进效果":"follow-up results",
        "信息收集":"Information gathering",
        "线索跟进":"Lead follow up",
        "需求挖掘":"Demand generation",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
	},
	"regex": [
		[/Budget/, "งบประมาณ"],
		[/^Something at start of text/, ""],
		[/This will be case insensitive/i, ""]
	]
};