Lang.prototype.pack.en = {
	"token": {
		//--货代物流部分
	   	"货代":"Freight forwarding",
	   	"月份":"Month",
	   	"客服得分":"Service",
	   	"价格得分":"Price",
	   	"仓储得分":"Warehouse",
	   	"投诉反馈得分":"Complaints",
	   	"总评分":"Total points",
	   	"评价详情":"Evaluation details",
	   	"备注":"Remarks",
	   	"修改原因":"Modify reason",
	   	"评价时间":"Evaluate time",
	   	"评价人":"Valuator",
	   	"创建者":"Creator",
	   	"上一次修改者":"Last modify user",
	   	"创建时间":"Create time",
	   	"修改时间":"Modify time",
	   	"类型":"Type",
	   	"社会信用代码":"Credit code",
	   	"办公地址":"Office address",
	   	"联系人":"Contacts",
	   	"联系电话":"Tel",
	   	"邮箱":"Email",
	   	"运输方式":"Transportation methods",
	   	"货代备注":"Freight forwarding remarks",
	   	"营业执照":"Business licence",
	   	"经营资格登记证":"Registration certificate",
	   	"合作时间":"Cooperate time",
	   	"综合评分":"Overall rating",
	   	"仓库":"Warehouse",
	   	"仓库面积":"Warehouse area",
	   	"是否危险":"Danger",
	   	"是否内装进港":"Built into the port",
	   	"仓库地址":"Warehouse address",
	   	"报表及时性":"Reports timely",
	   	"报表准确性":"Reports accurately",
	   	"入库":"Storage",
	   	"换包装":"Package",
	   	"盘库":"Check stock",
	   	"竞标记录":"Bid",
	   	"仓库名称":"Warehouse name",
	   	"月份":"Month",
	   	"货代订单":"Forwarder order",
	   	//--客户信息
	   	"客户联系人ID":"Linkman ID",
	   	"客户ID":"Customer ID",
	   	"姓名":"Name",
	   	"联系电话":"Link phone",
	   	"岗位":"Posts",
	   	"负责区域":"Response area",
	   	"是否在职":"On job",
	   	"性别":"Sex",
	   	"生日":"Birthday",
	   	"国籍":"Natonality",
	   	"影响力情况":"Infuence",
	   	"展会习惯":"Exhibition habits",
	   	"喜好":"Fancy",
	   	"饮食习惯":"Eating habits",
	   	"宗教信仰":"Faith",
	   	"是否默认":"Is default",
	   	"企业全称":"Full name",
	   	"企业简称":"Short name",
	   	"企业类型":"Customer type",
	   	"地区分类":"Area",
	   	"国家":"Country",
	   	"注册资金":"Registered funds",
	   	"注册地址":"Registered address",
	   	"经营范围":"Management scope",
	   	"中信保编号":"Sinosure number",
	   	"中信保信用评级":"Sinosure level",
	   	"百科备注":"Parent remarks",
	   	"企业电话":"Enterprise phone",
	   	"企业邮箱":"Enterprise email",
	   	"企业简介":"Enterprise profile",
	   	"发展历程":"Development course",
	   	"销售网络":"Sales network",
	   	"自定义字段":"Custome field",
	   	"企业信息完成度":"Customer completion",
	   	"年":"Year",
	   	"标准产品":"Product",
	   	"产品名称":"Product name",
	   	"年需求量":"Annual demands",
	   	"平均单价":"Average price",
	   	"供应商":"Supplier",
	   	"年采购量":"Purchase amount",
	   	"品牌":"Brand",
	   	"营销手段":"Marketing method",
	   	"年销量":"Year sales",
	   	"销售目的国":"Destination country",
	   	"主要采购商":"Main pruchaser",
	   	"企业性质":"Property",
	   	"企业性质备注":"Property remarks",
	   	"客户子公司备注":"Customer sub remarks",
	   	//--拜访客户
	   	"拜访记录":"Visit record",
	   	"客户联系人ID":"Linkman id",
	   	"单人费用":"Activity expens",
	   	"单人礼物":"Activity gift",
	   	"业务员id":"User id",
	   	"业务员名称":"User name",
	   	"开始时间":"Start time",
	   	"结束时间":"End time",
	   	"活动类型":"Activity type",
	   	"活动类型备注":"Activity remarks",
	   	"活动地点":"Activity address",
	   	"总活动费用":"Activity expense",
	   	"拜访对象备注":"Visit remarks",
	   	"活动摘要":"Activity summary",
	   	"客户级别":"Customer level",
	   	"客户状态":"Customer state",
	   	"客户流失备注":"Lost remarks",
	   	"是否有中国分公司":"China branch office",
	   	"是否有中方采购合同":"China contract",
	   	"资质文件":"Qualification documents",
	   	"销售客户备注":"Sale remarks",
	   	"机会来源类型":"Opportunity type",
	   	"机会来源说明":"Opportunity sources",
	   	"机会来源描述":"Price sensitive",
	   	"忠诚度":"Loyalty",
	   	"开始合作时间":"Cooperate time",
	   	"采购季节":"Procurement season",
	   	"紧密度":"Affinity",
	   	"活跃周期":"Active period",
	   	"合作备注":"Cooperate remarks",
	   	"总销售额":"Total sale money",
	   	"总最低销售售价":"Lowest sale money",
	   	"总维护费用":"Total maintenance costs",
	   	"总利润":"Total profits",
	   	"加工厂位置":"Factory locate",
	   	"工厂生产线":"Factory product line",
	   	"加工产品":"Factory product",
	   	"单据要求":"Document require",
	   	"对船公司要求":"Shipping agent require",
	   	"装箱要求":"Package require",
	   	"出运货物":"Goods type",
	   	"免用箱期":"Mianxiangqi",
	   	"免推期":"Miantuiqi",
	   	"是否可以转运":"Transport flag",
	   	"是否分批出运":"Batch flag",
	   	"交单地址要求":"Presentation address",
	   	"费用":"Expense",
	   	"礼物赠送":"Gift giving",
	   	"活动摘要":"Activity summary",
	   	//--加工厂
	   	"生产许可证":"Production licenses",
	   	"农药登记证":"Pesticide registration",
	   	"排污许可证":"Discharge permit",
	   	"工厂管理人员":"Factory manage person",
	   	"产品信息":"Product info",
	   	"工厂备注":"Factory remarks",
	   	"企业代码":"Enterprise code",
	   	//--客户产品
	   	"包材要求":"Ppackaging require",
	   	"特殊要求":"Special require",
	   	"产品浓度":"Concentration",
	   	"盐类":"Salt type",
	   	"其它盐":"Other salt name",
	   	"执行标准":"Execute standard",
	   	"执行标准号":"Execute numer",
	   	"标准备注说明":"Execute remarks",
	   	"产品特点":"Product feature",
	   	"产品要求":"Product demand",
	   	"加工成分":"Processing components",
	   	"理化指标":"Physical properities",
	   	"颜色属性":"Product color",
	   	"包装信息":"Package info",
	   	"执行标准":"Execute standard",
	   	"执行标准号":"Execute numer",
	   	"标准备注说明":"Execute remarks",
	   	"产品数量":"Product amount",
	   	"产品单位":"Product unit",
	   	"内包装要求":"Inside package require",
	   	"内包装要求单位":"Inside package require unit",
	   	"内包装要求名称":"Inside package require name",
	   	"外包装要求":"Outside package require",
	   	"外包装要求单位":"Outside package require unit",
	   	"外包装要求名称":"Outside package require name",
	   	"标准内包装id":"Inside package id",
	   	"标准内包装名称":"Inside package name",
	   	"标准内包装信息":"Inside package info",
	   	"标准内包装价格":"Inside package price",
	   	"标准外包装id":"Outside package id",
	   	"标准外包装名称":"Outside package name",
	   	"标准外包装信息":"Outside package info",
	   	"标准外包装价格":"Outside package price",
	   	"标准辅材id信息":"Sub package info",
	   	"标准辅材价格":"Sub package price",
	   	"加工成分费用":"Processing price",
	   	"颜色属性":"Product color",
	   	"图片信息":"Image info",
	   	"运输信息":"Freight info",
	   	"运输价格":"Freight price",
	   	"内部供货单位":"Inside unit",
	   	"内部核算价":"Inside price",
	   	"交货时间":"Delivery date",
	   	"单据要求":"Documentary require",
	   	"对船公司要求":"Shipping agent require",
	   	"装箱要求":"Package require",
	   	"出运货物":"Goods type",
	   	"免箱期":"Free detention",
	   	"免堆期":"Free demurrage",
	   	"是否可以转运":"Transport flag",
	   	"是否分批出运":"Batch flag",
	   	"柜子规格":"Cupboard type",
	   	"整柜数量":"Cupboard per number",
	   	"柜数":"Cupboard number",
	   	"海运费估算":"Ocean freight",
	   	"港杂费":"Port surcharge",
	   	"出口退税率":"Tax free",
	   	"最低销售价":"Min sell price",
	   	"合同单价":"Contract price",
	   	//--商机
	   	"商机名称":"Business name",
	   	"商机来源":"Business from",
	   	"商机状态":"Business state",
	   	"预计收益":"Expect income",
	   	"成功概率":"Success probability",
	   	"商机描述":"Business describe",
	   	"商机备注":"Business remarks",
	   	"失败原因":"Fail reason",
	   	"币种":"Currency",
	   	"汇率":"Exchange rate",
	   	"付款方式":"Pay type",
	   	"账期":"Payment days",
	   	"目的港":"Destination port",
	   	"目的国家":"Destination country",
	   	"贸易方式":"Trade type",
	   	"贸易方式说明":"Trade descripe",
	   	"佣金方式":"Commission mode",
	   	"佣金率":"Commission percent",
	   	"信保赔付率":"Credit rate",
	   	"福华收款银行":"Bank",
	   	"订单总价":"Total order price",
	   	"跟进内容":"Follow content",
	   	"跟进效果":"Follow effect",
	   	"商机阶段":"Business process",
	   	"转化状态":"Transform state",
	   	//--知识库
	   	"问题标题":"title",
	   	"解决方案":"solution",
	   	"文档资源地址":"resource_url",
	   	"包装参数":"package_param_detail",
	   	"颗粒剂加工费":"granule_processing_fee",
	   	"成分价格":"component_price",
	   	"管理费用":"management_fee",
	   	"港杂费":"terminal_handing_charges",
	   	"运费维护":"transportation_fee",
	   	"水剂加工费":"wateragent_fee",
	   	"展会名称":"name",
	   	"城市":"city",
	   	"展会地址":"address",
	   	"开始时间":"start_time",
	   	"结束时间":"end_time",
	   	"主办方":"sponsor",
	   	"承办方":"organizer",
	   	"展会介绍":"introduce",
	   	"展会链接":"link_url",
		//--hahaha
		"客户信息":"Consumers",
		"客户列表":"Consumers list",
		"供应商信息":"Suppliers",
		"加工厂":"Processing plant",
		"货代物流":"Freight agent & Logistics",
		"销售统计":"Sales statistics",
		"商机":"Business opportunity",
		"销售动态":"Sales dynamic",//?
		"费用与利润":"Cost & Profit",
		"客户维护":"Customer care",
		"利润统计":"Profit statistics",
		"我的历史订单":"My history Order",//?
		"市场数据":"Market data",
		"行业数据":"Industry data",
		"知识库":"Knowledge",
		"产品常见问题":"Product's FAQ",
		"营销培训":"Sales Training",
		"客户产品包装要求":"Customization package",
		"标准产品档案":"Standard products",
		"包材档案":"Packages",
		"包材成本参考":"Packing cost",
		"加工成本参考":"Processing cost",
		"百科":"Encyclopedia",
		"展会动态":"Exhibition dynamic",
		"其他":"Else",
		"决策支持":"Decision",
		"销售数据":"Sale data",
		"成本费用":"Cost",
		"数据库":"Database",
		"系统管理":"System",
		"权限设置":"Purview setting",
		"数据字典维护":"Data dictionary maintenance",
		"修改密码":"Modify password",
		"退出":"Exit",
		"当前位置":"Position",
		"上一页":"Previous Page",
		"下一页":"Next Page",
		"确定":"Confirm",
		"取消":"Cancel",
		"完成":"Finished",
		"继续添加产品":"Continue to add products",
		"输入关键词查找":"Enter keywords",
		"搜索":"Search",
		"新增":"Add",
		"基本信息":"Basic info",
		"市场信息":"Market info",
		"订单信息":"Order info",
		"关联数据":"Related data",
		"订单默认要求":"Order default request",
		"沟通记录":"Communication record",
		"编辑":"Edit",
		//--树形结构部分
		"美洲":"America",
		"亚洲":"Asia",
		"欧洲":"Europe",
		"非洲":"Africa",
		"大洋洲":"Oceania",
		"南美洲":"South America",
		"北美洲":"North America",
		"东亚":"East Asia",
		"韩国":"South korea",
		"日本":"Japan",
		"朝鲜":"North Korea",
		"东南亚":"Southeast Asia",
		"西亚":"west Asia",
		"南亚":"South Asia",
		"西欧":"Western Europe",
		"东欧":"Eastern Europe",
		"北欧":"Northern Europe",
		"南非":"South Africa",
		"加纳":"Ghana",
		"澳大利亚":"Australia",
		"新西兰":"New Zealand",
		"订单记录":"Order record",
		"调价记录":"Adjust price record",
		"延付款记录":"Delay payment record",
		"合同取消记录":"Contract cancel record",
		//--下拉框部分
		"合作客户":"Cooperative client",
		"潜在客户":"Potential customer",
		"流失客户":"Lossing customer",
		"信用评级":"Credit rating",
		"企业性质":"Enterprise property",
		"分销商":"Distributor",//?
		"经销商":"Wholesaler",//?
		"终端客户":"Terminal clients",
		"客户类型":"Client type",
		"战略客户":"Strategic client",
		"大客户":"Major client",//?
		"重要客户":"Important client",//?
		"一般客户":"Ordinary client",
		"风险客户":"Unstable customers",
		"客户状态":"Customer status",
		"正常":"Normal",
		"客户编号":"Customer ID",
		"易流失":"Instability",
		"销售组织":"Marketing organizing",
		"全部":"All",
		"付款方式":"Payment method",
		"预付":"Advance payment",
		"账期":"Payment days",
		"补贴":"Subsidy",
		"调价方式":"Adjust price method",
		"上调":"Up-regulation",
		"下调":"Down-regulation",
		"是":"Yes",
		"否":"No",
		//--表格部分
		"客户全称":"รูปภาพสถานที่",
		"客户简称":"รูปภาพสถานที่",
		"国家":"รูปภาพสถานที่",
		"开始合作时间":"รูปภาพสถานที่",
		"合作时间（月）":"รูปภาพสถานที่",
		"活跃周期":"รูปภาพสถานที่",
		"合同总金额（万元）":"รูปภาพสถานที่",
		"总最低销售限价（万元）":"รูปภาพสถานที่",
		"总维护费用（万元）":"รูปภาพสถานที่",
		"总利润（万元）":"รูปภาพสถานที่",
		"产品名称":"รูปภาพสถานที่",
		"产品种类":"รูปภาพสถานที่",
		"总销售量":"รูปภาพสถานที่",
		"采购产品":"รูปภาพสถานที่",
		"供应商":"รูปภาพสถานที่",
		"年需求量":"รูปภาพสถานที่",
		"年采购量":"รูปภาพสถานที่",
		"平均单价（美元）":"รูปภาพสถานที่",
		"销售产品":"รูปภาพสถานที่",
		"品牌":"รูปภาพสถานที่",
		"营销手段":"รูปภาพสถานที่",
		"年销售量":"รูปภาพสถานที่",
		"销售目的国":"รูปภาพสถานที่",
		"所占市场份额":"รูปภาพสถานที่",
		"合作情况":"รูปภาพสถานที่",
		"价格敏感度":"รูปภาพสถานที่",
		"忠诚度":"รูปภาพสถานที่",
		"采购季节":"รูปภาพสถานที่",
		"合作紧密度（福华是否独家供应）":"รูปภาพสถานที่",
		"活跃周期":"รูปภาพสถานที่",
		"备注":"รูปภาพสถานที่",
		"编号":"รูปภาพสถานที่",
		"姓名":"รูปภาพสถานที่",
		"岗位":"รูปภาพสถานที่",
		"是否在职":"รูปภาพสถานที่",
		"负责区域":"รูปภาพสถานที่",
		"性别":"รูปภาพสถานที่",
		"国籍":"รูปภาพสถานที่",
		"联系电话":"รูปภาพสถานที่",
		"邮箱":"รูปภาพสถานที่",
		"是否默认":"รูปภาพสถานที่",
		"产品序列号":"รูปภาพสถานที่",
		"品名":"รูปภาพสถานที่",
		"品类":"รูปภาพสถานที่",
		"包装规格":"รูปภาพสถานที่",
		"产品参数":"รูปภาพสถานที่",
		"包装参数":"รูปภาพสถานที่",
		"订单编号":"รูปภาพสถานที่",
		"外销合同号":"รูปภาพสถานที่",
		"合同成本价（万元）":"รูปภาพสถานที่",
		"是否投诉":"รูปภาพสถานที่",
		"是否调价":"รูปภาพสถานที่",
		"利润（万元）":"รูปภาพสถานที่",
		"是否质押":"รูปภาพสถานที่",
		"合同时间":"รูปภาพสถานที่",
		"调价单价金额":"รูปภาพสถานที่",
		"合同价总变更":"รูปภาพสถานที่",
		"调价原因":"รูปภาพสถานที่",
		"操作人":"รูปภาพสถานที่",
		"调价日期":"รูปภาพสถานที่",
		"发票号":"รูปภาพสถานที่",
		//--表单部分
		"中信保编码":"รูปภาพสถานที่",
		"查看报告":"รูปภาพสถานที่",
		"注册资金（美元）":"รูปภาพสถานที่",
		"企业电话":"รูปภาพสถานที่",
		"企业邮箱":"รูปภาพสถานที่",
		"注册地址":"รูปภาพสถานที่",
		"经营范围":"รูปภาพสถานที่",
		"是否有中国分公司":"รูปภาพสถานที่",
		"是否有中方采购":"รูปภาพสถานที่",
		"工厂位置":"รูปภาพสถานที่",
		"生产线":"รูปภาพสถานที่",
		"产品":"รูปภาพสถานที่",
		"产能":"รูปภาพสถานที่",
		"备注":"รูปภาพสถานที่",
		"创建人":"รูปภาพสถานที่",
		"创建时间":"รูปภาพสถานที่",
		"客户百科":"รูปภาพสถานที่",
		"企业简介":"รูปภาพสถานที่",
		"发展历程":"รูปภาพสถานที่",
		"销售网络":"รูปภาพสถานที่",
		"自定义字段":"รูปภาพสถานที่",
		"最后编辑人":"รูปภาพสถานที่",
		"编辑时间":"รูปภาพสถานที่",
		"开始时间":"รูปภาพสถานที่",
		"结束时间":"รูปภาพสถานที่"
	},
	"regex": [
		[/Budget/, "งบประมาณ"],
		[/^Something at start of text/, ""],
		[/This will be case insensitive/i, ""]
	]
};