
package com.fuhuadata.manager.impl.NCExchange.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "M5715FileManagerWsPortType", targetNamespace = "http://et.itf.nc/M5715FileManagerWs")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface M5715FileManagerWsPortType {


    /**
     * 
     * @param byteItem
     * @param string
     * @param _long
     * @param string1
     * @param string2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:crmExchangeFileToNC")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crmExchangeFileToNC", targetNamespace = "http://et.itf.nc/M5715FileManagerWs", className = "com.fuhuadata.manager.impl.NCExchange.services.CrmExchangeFileToNC")
    @ResponseWrapper(localName = "crmExchangeFileToNCResponse", targetNamespace = "http://et.itf.nc/M5715FileManagerWs", className = "com.fuhuadata.manager.impl.NCExchange.services.CrmExchangeFileToNCResponse")
    public String crmExchangeFileToNC(
            @WebParam(name = "byteItem", targetNamespace = "")
                    byte[] byteItem,
            @WebParam(name = "string", targetNamespace = "")
                    String string,
            @WebParam(name = "long", targetNamespace = "")
                    Long _long,
            @WebParam(name = "string1", targetNamespace = "")
                    String string1,
            @WebParam(name = "string2", targetNamespace = "")
                    String string2);

}
